---
title: "Estimators.1"
author: "GMcGuire"
date: "2026-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading in our dataset and merging
# I had problems with RAM earlier, but emailed Mebane and he provided the code - GM

library(haven)

tf_household <- tempfile()
this_url_household <-
    "https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/sas_hmi.zip"
download.file( this_url_household , tf_household , mode = 'wb' )
unzipped_files_household <- unzip( tf_household , exdir = tempdir() )
acs_sas_household <-
    grep( '\\.sas7bdat$' , unzipped_files_household , value = TRUE )
acs_df_household <- read_sas( acs_sas_household )
dim(acs_df_household)
#> dim(acs_df_household)
#[1] 51390   241
names( acs_df_household ) <- tolower( names( acs_df_household ) )

tf_person <- tempfile()
this_url_person <-
    "https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/sas_pmi.zip"
download.file( this_url_person , tf_person , mode = 'wb' )
unzipped_files_person <- unzip( tf_person , exdir = tempdir() )
acs_sas_person <-
    grep( '\\.sas7bdat$' , unzipped_files_person , value = TRUE )
acs_sas_person   
#> acs_sas_person   
#[1] "/tmp/RtmphVxQ4z/psam_p26.sas7bdat"
acs_df_person <- read_sas( acs_sas_person )
dim(acs_df_person)
#> dim(acs_df_person)
#[1] 102725    286
names( acs_df_person ) <- tolower( names( acs_df_person ) )

acs_df_household[ , 'rt' ] <- NULL
acs_df_person[ , 'rt' ] <- NULL
acs_df <- merge( acs_df_household , acs_df_person )
dim(acs_df);
stopifnot( nrow( acs_df ) == nrow( acs_df_person ) )
acs_df[ , 'one' ] <- 1
dim(acs_df);
#> dim(acs_df);
#[1] 102725    520

save(acs_df, file="merged_ACS_MI2024.RData")

library(survey)
acs_design <-
    svrepdesign(
        weight = ~pwgtp ,
        repweights = 'pwgtp[0-9]+' ,
        scale = 4 / 80 ,
        rscales = rep( 1 , 80 ) ,
        mse = TRUE ,
        type = 'JK1' ,
        data = acs_df
    )

dim(acs_design)
```

```{r}
# variable recording (from helper data)
acs_design <-
    update(
        
        acs_design ,
        
        state_name =
            factor(
                as.numeric( state ) ,
                levels = 
                    c(1L, 2L, 4L, 5L, 6L, 8L, 9L, 10L, 
                    11L, 12L, 13L, 15L, 16L, 17L, 18L, 
                    19L, 20L, 21L, 22L, 23L, 24L, 25L, 
                    26L, 27L, 28L, 29L, 30L, 31L, 32L, 
                    33L, 34L, 35L, 36L, 37L, 38L, 39L, 
                    40L, 41L, 42L, 44L, 45L, 46L, 47L, 
                    48L, 49L, 50L, 51L, 53L, 54L, 55L, 
                    56L, 72L) ,
                labels =
                    c("Alabama", "Alaska", "Arizona", "Arkansas", "California", 
                    "Colorado", "Connecticut", "Delaware", "District of Columbia", 
                    "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", 
                    "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", 
                    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", 
                    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", 
                    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
                    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
                    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", 
                    "Washington", "West Virginia", "Wisconsin", "Wyoming", "Puerto Rico")
            ) ,
        
        cit =
            factor( 
                cit , 
                levels = 1:5 , 
                labels = 
                    c( 
                        'born in the u.s.' ,
                        'born in the territories' ,
                        'born abroad to american parents' ,
                        'naturalized citizen' ,
                        'non-citizen'
                    )
            ) ,
        
        poverty_level = as.numeric( povpip ) ,
        
        married = as.numeric( mar %in% 1 ) ,
        
        sex = factor( sex , labels = c( 'male' , 'female' ) )
    )
```


```{r}


```
